# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: scheduler_to_trainer.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1ascheduler_to_trainer.proto\"\x13\n\x11QueryStatsRequest\"1\n\x12QueryStatsResponse\x12\x1b\n\x13\x66inished_iterations\x18\x01 \x01(\r2M\n\x12SchedulerToTrainer\x12\x37\n\nQueryStats\x12\x12.QueryStatsRequest\x1a\x13.QueryStatsResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'scheduler_to_trainer_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_QUERYSTATSREQUEST']._serialized_start=30
  _globals['_QUERYSTATSREQUEST']._serialized_end=49
  _globals['_QUERYSTATSRESPONSE']._serialized_start=51
  _globals['_QUERYSTATSRESPONSE']._serialized_end=100
  _globals['_SCHEDULERTOTRAINER']._serialized_start=102
  _globals['_SCHEDULERTOTRAINER']._serialized_end=179
# @@protoc_insertion_point(module_scope)
